---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employee-svc
  name: employee-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-svc
  template:
    metadata:
      labels:
        app: employee-svc
    spec:
      containers:
      - image: employee-svc
        name: employee-svc
        ports:
        - containerPort: 9090
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-svc
  name: employee-svc
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: employee-svc
  type: LoadBalancer
status:


